- components/integration/integration.php
- readme.txt
- woocommerce-convertkit.php
Added a requested feature to have a toggle for sending first name, last name, or both to CK's 'name' field.
Also, added a Settings link from the plugins page. Our docs reference this. 
@davidlamarwheeler please review and approve.
> Release 1.0.3

- components/integration/integration.php
> Fixing helper text.

- components/integration/integration.php
> Updating version specific property access. Fix #14.

- .gitignore
- components/integration/integration.php
- functions/convertkit.php
- readme.txt
- woocommerce-convertkit.php
This PR adds a setting to enable purchase data to be sent to CK. 
When the subscription event happens the data is sent to the CK API `/purchase` endpoint.
> Adding payment code.

- components/integration/functions/integration.php
- components/integration/integration.php
Fix #27 
Add an order note to the WooCommerce order with all tags that were applied to the customer.
> Add order note when customer tagged.

- components/integration/functions/integration.php
- components/integration/integration.php
- components/integration/views/meta-box.php
- functions/convertkit.php
> Add textdomain to all translatable strings output by the plugin

- components/integration/integration.php
> Make plugin settings link work with other WooCommerce addons

- components/integration/integration.php
> Correct product metabox title

- components/integration/functions/integration.php
> Display tags/forms/sequences alphabetically

- components/integration/functions/integration.php
- components/integration/integration.php
- components/integration/resources/integration.js
> Add ability to refresh subscription options on settings page

- components/integration/integration.php
> Add integration name to purchase API requests

- components/integration/integration.php
When check and CoD orders are marked 'complete', purchase data will be sent to ConvertKit.
https://app.intercom.io/a/apps/e4n3xtxz/inbox/inbox/3066130/conversations/24630795225
> Add support for sending CoD and check payments to ConvertKit

- .scripts/read-actions-filters.php
- admin/class-ckwc-admin-product.php
- composer.lock
- includes/class-ckwc-integration.php
- includes/functions.php
- phpcs.xml
- resources/backend/css/product.css
- resources/backend/css/select2.css
- resources/backend/js/select2.js
- tests/_support/Helper/Acceptance.php
- tests/acceptance/ProductCest.php
Any ConvertKit account that contains a large number of Forms, Tag and/or Sequences results in a lengthly select dropdown when choosing an option:
This isn't user friendly or intuitive when trying to find a specific Form, Tag or Sequence.
Similar to the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/270), this PR adds jQuery Select2, which replaces select dropdowns for selecting a Form, Tag or Sequence, to provide a scrollable selection list with search functionality.
Before:
After:
The following tests have been modified to test that Select2 works when selecting a Form, Tag or Sequence:
- `PurchaseDataCest`
- `SubscribeOnOrderCreatedEventCest`
- `SubscribeOnOrderProcessingEventCest`
- `SubscribeOnOrderCompletedEventCest`
- `SettingNameFormatCest`
The …
> Use Select2 for improved <select> dropdowns for Form / Tag / Sequence selection.

- .github/workflows/coding-standards.yml
- .github/workflows/test.yml
- tests/_support/Helper/Acceptance/WooCommerce.php
- tests/acceptance.suite.yml
Run tests against WordPress 6.2 RC2
> Run tests against WordPress 6.2 RC2

- .github/workflows/coding-standards.yml
- .github/workflows/test.yml
- readme.txt
- tests/_support/Helper/Acceptance/Plugin.php
- tests/wpunit/ResourceTagsTest.php
- woocommerce-convertkit.php
Run tests against ‘latest’ (WordPress 6.2)
> Run tests against ‘latest’ (WordPress 6.2), WooCommerce 7.5.1

- .github/workflows/coding-standards.yml
- .github/workflows/deploy.yml
- .github/workflows/test.yml
Use GitHub Checkout Action v4, released today.
> Use GitHub Checkout Action v4

- composer.json
Update the ConvertKit WordPress Libraries to `1.4.0`
> Update WordPress Libraries to `1.4.0`

- composer.json
Use WordPress Libraries 1.4.2, which includes a [more secure logging method](https://github.com/ConvertKit/convertkit-wordpress-libraries/pull/34).
This logging isn't used by the ConvertKit for WooCommerce Plugin, as it uses WooCommerce's built in `WC_Logger` class - but best to keep our libraries updated across all Plugins.
> Use WordPress Libraries 1.4.2

- composer.json
Updates the Plugin to use the [2.0.2 release](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/2.0.2) of the WordPress Libraries
> Use WordPress Libraries `2.0.2`

- composer.json
Uses 2.0.3 of the WordPress Libraries.
> Use WordPress Libraries 2.0.3

- README.md
- resources/backend/css/settings.css
- tests/_support/Helper/Acceptance/Plugin.php
- woocommerce-convertkit.php
- Renames ConvertKit to Kit in the readme.md file
- Changes the Author name from ConvertKit to Kit
- Tweaks to the UI to better match the new app.kit.com UI, including hover states on buttons, text colors and border radius on panels
Before:
After:
> Branding Fixes

- readme.txt
- woocommerce-convertkit.php
Updates GPL to v3, as we use for the other Kit Plugins.
> Update GPL to v3

- .github/workflows/test-backward-compat.yml
- .github/workflows/test.yml
Exchanges a v3 API Key and Secret for OAuth tokens, as currently OAuth tokens have to be manually generated and updated in Settings > Secret and Variables > Actions every ~ 2 days, due to their expiry. 
> Tests: Exchange API Key and Secret for OAuth Tokens

- composer.json
Adds alias commands:
| Command | Description |
|---------|-------------|
| `coding-standards` | Runs WordPress and PHP Coding Standards on the entire plugin codebase |
| `fix-coding-standards` | Fix PHP files to meet WordPress and PHP Coding Standards |
| `coding-standards-on-tests` | Runs PHP Coding Standards on the /tests folder |
| `fix-coding-standards-on-tests` | Fix PHP files to meet PHP Coding Standards on the /tests folder |
| `static-analysis` | Runs PHPStan static analysis with increased memory limit |
> Alias Composer Commands
