Kit/convertkit-woocommerce

components/integration/integration.php

This changes the extension's settings to allow On-Hold to be chosen as the subscribe event. If this option is selected, then customers with orders which move to the On-Hold status will be sent to ConvertKit as subscribers.
Closes #57

Allow On-Hold order status as the subscribe event

---

components/integration/functions/integration.php
components/integration/integration.php
components/integration/views/meta-box.php
functions/convertkit.php
functions/utility.php
phpcs.xml.dist
woocommerce-convertkit.php

Brings over the `convertkit-wordpress` PHPCS rules and cleans up PHP files according to those already-established rules.

PHPCS Cleanup

---

includes/class-ckwc-integration.php
includes/class-ckwc-order.php
includes/class-ckwc-resource-custom-fields.php
includes/class-ckwc-resource.php
resources/backend/js/integration.js
tests/_support/Helper/Acceptance.php
tests/acceptance/SettingCustomFieldsCest.php
tests/acceptance/SubscribeOnOrderCompletedEventCest.php
tests/acceptance/SubscribeOnOrderCreatedEventCest.php
tests/acceptance/SubscribeOnOrderProcessingEventCest.php
views/backend/custom-field-dropdown-field.php
views/backend/product/disabled.php
views/backend/product/meta-box.php
views/backend/settings/custom-field-disabled.php
views/backend/settings/custom-field.php
views/backend/settings/subscription-disabled.php
woocommerce-convertkit.php

Adds configuration options to map WooCommerce Order Data (Phone Number, Billing Address, Shipping Address, Payment Method, Customer Note) to the subscriber's Custom Fields in ConvertKit, as partly requested at https://wordpress.org/support/topic/push-phone-to-convertkit-from-woocommerce-orders/
New settings introduced at WordPress Admin > WooCommerce > Settings > Integrations > ConvertKit:
Example of Order data mapped to a subscriber in ConvertKit:
- `SettingCustomFieldsCest`: Added tests to confirm that defining Custom Field mappings in the Plugin's settings saves correctly.
- `SubscribeOnOrderProcessingEventCest`: Added tests to check custom fields do, or do not, get sent to ConvertKit, depending on the Plugin configuration.

Map Order Data to Custom Fields

---

includes/class-ckwc-integration.php
tests/_support/Helper/Acceptance.php
tests/acceptance/SettingNameFormatCest.php
tests/acceptance/SettingSubscribeEventCest.php
tests/acceptance/SubscribeOnOrderPendingPaymentEventCest.php

WooCommerce Orders don't have a "Created" status.  When an Order is created, it is initially assigned the "Pending payment" status.
This PR changes the integration's settings to match the same labels as used in WooCommerce Orders, and adds a more verbose description to the settings field to reflect https://woocommerce.com/document/managing-orders/
The underlying setting field's value, `pending` is accurate, and does not need to be changed.
- `SettingNameFormatCest`: Use 'Order Payment processing' instead of 'Order Created' when selecting the Subscription Event by its label
- `SettingSubscribeEventCest`: Updated tests to use 'Order Payment processing' instead of 'Order Created' when selecting the Subscription Event by its label
- `SubscribeOnOrderPendingPaymentEventCest`: Again, use 'Order …

Change Subscription "Order Created" label to "Order Pending payment"

---

.github/workflows/test.yml
tests/_support/Helper/Acceptance.php
tests/acceptance/PurchaseDataCest.php

Purchase Data tests run in parallel across different environments may hit a race condition when retrieving a specific purchase from the `purchases` API endpoint, as evidenced [here](https://github.com/ConvertKit/convertkit-woocommerce/pull/93/checks), resulting in tests incorrectly failing:
In the above example, the following steps happened in order:
- purchase data tests were started by GitHub's action on PHP 7.2, 7.3, 7.4 and 8.0 in parallel
- the test on PHP 7.2 created purchase data on ConvertKit with the WooCommerce Order ID 20 with email address `wordpress-2022-03-28-13-09-32-php-70234@convertkit.com` at 13:09:32
- the test on PHP 8.0 created purchase data on ConvertKit with the WooCommerce Order ID 20 with email address `wordpress-2022-03-28-13-09-33-php-80016@convertkit.com` at …

Fix Order ID Race Condition in Purchase Data Tests

---

.distignore
.github/workflows/test.yml
.gitignore
admin/class-ckwc-admin-ajax.php
admin/class-ckwc-admin-product.php
composer.json
includes/class-ckwc-api.php
includes/class-ckwc-checkout.php
includes/class-ckwc-integration.php
includes/class-ckwc-order.php
includes/class-ckwc-resource.php
includes/class-ckwc-review-request.php
includes/class-ckwc-wc-subscriptions.php
includes/class-wp-ckwc.php
includes/functions.php
phpstan.neon.dist
phpstan.neon.example
woocommerce-convertkit.php

[PHPStan](https://phpstan.org/blog/find-bugs-in-your-code-without-writing-tests) performs static analysis on the Plugin's PHP code.  This adds to our tests, PHP Coding Standards and WordPress Coding Standards by ensuring:
- DocBlocks declarations are valid and uniform
- DocBlocks declarations for WordPress `do_action()` and `apply_filters()` calls are valid
- Typehinting variables and return types declared in DocBlocks are correctly cast
- Any unused functions are detected
- Unnecessary checks / code is highlighted for possible removal
- Conditions that do not evaluate can be fixed/removed as necessary
This isn't a replacement for writing tests; rather, an addition to ensure our code continues to meet the high standards expected, reducing ambiguity on how code should be written and …

Add PHPStan for Static Analysis

---

includes/class-ckwc-resource-custom-fields.php
includes/class-ckwc-resource-forms.php
includes/class-ckwc-resource-sequences.php
includes/class-ckwc-resource-tags.php
includes/class-ckwc-resource.php
tests/wpunit/ResourceCustomFieldsTest.php
tests/wpunit/ResourceFormsTest.php
tests/wpunit/ResourceSequencesTest.php
tests/wpunit/ResourceTagsTest.php
views/backend/custom-field-dropdown-field.php
views/backend/subscription-dropdown-field.php

Implements cached resource expiration, as we do in the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/302).
- `WPUnit` tests updated to confirm resource cache expiration is honored

Add expiration to cached resources

---

phpstan.neon.dist
tests/_support/Helper/Acceptance/WooCommerce.php

PHPStan 1.7 better detects some WordPress constants and fixes some false positives, which can be safely removed from the `phpstan.neon.dist` configuration, similar to the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/316).

Updated PHPStan configuration to support PHPStan 1.7

---

.github/workflows/test.yml

Updates GitHub Action to test using WordPress 6.0, released May 24th.
Uses existing tests.

Run tests against WordPress 6.0

---

.github/workflows/test.yml
includes/class-ckwc-integration.php
phpstan.neon.dist
phpstan.neon.example
tests/acceptance/SyncPastOrdersCest.php

Fixes PHPStan's configuration for GitHub actions by:
- Changing `scanDirectories` to scan the WordPress Plugins directory to build symbols (function definitions and constants), rather than scanning the entire WordPress installation, because the `includes` configuration already points to phpstan-wordpress' WordPress symbol definitions.  Scanning the entire WordPress installation is slower and results in [false positive errors](https://github.com/ConvertKit/convertkit-woocommerce/runs/6677864876?check_suite_focus=true).
- Changing `ignoreErrors` to ignore some WordPress symbols that aren't yet detected by PHPStan.
Existing tests should pass to confirm this PR works.

Fix PHPStan Configuration

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test.yml
README.md
readme.txt

Updates GitHub Actions for coding standards and tests to run when changes are pushed to the `main` branch since it has been renamed from `master` in GitHub.
Updates links to markdown files to reflect the change of branch name.
Existing tests should run on this PR and when this PR is merged.

Change references from `master` to `main`

---

.github/workflows/test.yml
admin/class-ckwc-admin-product.php
composer.json
includes/class-ckwc-api.php
includes/class-ckwc-checkout.php
includes/class-ckwc-integration.php
lib/class-convertkit-api.php
lib/class-convertkit-resource.php
views/backend/settings/custom-field.php
views/backend/settings/link-button.php
views/backend/settings/subscription.php
views/backend/settings/sync-past-orders-button.php
views/backend/subscription-dropdown-field.php
woocommerce-convertkit.php

Replaces `phpcs:ignore` comments with the specific rule to ignore, such as `phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter`.
This ensures the coding standard checks for lines containing an ignore directive will still validate the code against other coding standard rules.
Existing tests pass to confirm no breaking changes.

Improve reasons to ignore coding standards

---

.github/workflows/test.yml
tests/_data/dump.sql

Runs tests against the latest WordPress version, 6.0.1, on GitHub's actions.
Updates the database dump structure to match that used by WordPress 6.0.1.

Run Tests against WordPress 6.0.1

---

lib/class-convertkit-resource.php

As with the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/337), prevents querying the API on every WordPress Administration screen request if a ConvertKit account does not have a particular resource (such as forms or tags).  The frontend site is unaffected, as no API queries are made.
If a ConvertKit account has no resources (forms or tags), the plugin's cache for these resources will be empty.
As a result, the plugin would query the API on every WordPress administration screen request, resulting in slow loading times (in this example, approximately ~ 1.4 seconds is added to the load time for an administration screen):
Whilst the account _should_ have at least one form, tag or sequence (the plugin isn't really useful otherwise), it's wrong for the plugin …

Plugin Performance when no Resources exist

---

admin/class-ckwc-admin-product.php
admin/class-ckwc-admin-quick-edit.php
includes/class-wp-ckwc.php
resources/backend/js/quick-edit.js
tests/_support/Helper/Acceptance/WPQuickEdit.php
tests/acceptance.suite.yml
tests/acceptance/ProductCest.php
views/backend/product/quick-edit.php
woocommerce-convertkit.php

Similar to the [main ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/335), adds options to WordPress' [Quick Edit](https://wordpress.com/support/pages/edit-pages-screen/#quick-edit) functionality to change the ConvertKit Form, Tag or Sequence to subscribe the customer to for a given WooCommerce Product
Video:
https://www.loom.com/share/c941acbdf0a44a6d8c34af518c36d366
- `ProductCest:testQuickEditUsingDefinedResource`: Tests that using the Quick Edit functionality on an existing WooCommerce Product works when choosing a specific resource.

Quick Edit

---

admin/class-ckwc-admin-refresh-resources.php
includes/class-wp-ckwc.php
lib/class-convertkit-resource.php
resources/backend/js/quick-edit.js
resources/backend/js/refresh-resources.js
tests/_support/Helper/Acceptance/WPBulkEdit.php
tests/_support/Helper/Acceptance/WPQuickEdit.php
tests/acceptance/RefreshResourcesButtonCest.php
views/backend/product/bulk-edit.php
views/backend/product/meta-box.php
views/backend/product/quick-edit.php
views/backend/subscription-dropdown-field.php
woocommerce-convertkit.php

Similar to the [ConvertKit Plugin](https://github.com/ConvertKit/convertkit-wordpress/pull/339), adds a refresh button next to the subscription setting on WooCommerce Products, to refresh the cached forms, sequences and tags from the API.
- adding/editing Products
- quick/bulk editing Products
This solves two issues:
1. Currently, only WordPress Administrators have access to forcing a refresh of resources by navigating to the `WooCommerce > Settings > Integrations > ConvertKit` screen.  WordPress Editors and Authors do not have access to this screen, which is standard WordPress behaviour - however, Editors and Authors in WordPress can create/edit Products, and configure the per-Product subscription setting for ConvertKit.
2.  There can be confusion when a ConvertKit user (whether a …

Add Refresh Button to Products

---

.github/workflows/test.yml

Run tests against WordPress 6.1 RC5, head of WordPress 6.1's formal release on ~ 1st November 2022.

Run tests against WordPress 6.1 RC5

---

.github/workflows/coding-standards.yml
.github/workflows/test.yml

Run Tests and Coding Standards against WordPress 6.1, released November 1st.

Run Tests and Coding Standards against WordPress 6.1

---

admin/class-ckwc-admin-bulk-edit.php
admin/class-ckwc-admin-quick-edit.php
includes/class-ckwc-integration.php
includes/class-ckwc-order.php
includes/class-ckwc-wc-subscriptions.php
tests/_support/Helper/Acceptance/Plugin.php

Fixes failing static analysis tests due to improvements in static analysis in PHPStan for WordPress 1.1.5.
Fixes an issue with tests when deactivating WooCommerce Stripe Gateway after WooCommerce would result in a fatal error, due to WooCommerce.

PHPStan for WordPress 1.1.5 compatbility

---

.github/workflows/coding-standards.yml
.github/workflows/test.yml

Uses `latest` for `wp-versions`, so that tests and coding standards always run against the latest stable release of WordPress, to save having to change the version number every time there's a WordPress update.

Run Tests against latest stable WordPress version

---

admin/class-ckwc-admin-bulk-edit.php
resources/backend/css/bulk-quick-edit.css
views/backend/product/bulk-edit.php
views/backend/product/quick-edit.php

- Improves layout, spacing and sizing of elements when using the Bulk Edit and Quick Edit functionality in WordPress on varying screen sizes
- Increase size of refresh buttons on smaller screens
Desktop
Mobile
Desktop
Mobile

Improve Bulk & Quick Edit UI

---

.github/workflows/test.yml

Runs tests against PHP 8.1, which is the current (and only) [actively supported version](https://www.php.net/supported-versions.php) provided by PHP.
`WP_DEBUG` is disabled when running tests against PHP 8.1, due to [this WordPress core](https://core.trac.wordpress.org/ticket/54504) issue that requires resolution to prevent `E_DEPRECATED` notices when performing HTTP requests.
Critical PHP errors and warnings will still result in test failure, however we'll need to reintroduce WP_DEBUG once WordPress resolve the above core issue.

Run tests against PHP 8.1

---

composer.json
includes/class-ckwc-api.php

Updates the Plugin to use the latest version of our ConvertKit WordPress Libraries, [1.2.3](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/1.2.3), resolving [this issue](https://convertkit.atlassian.net/browse/T3-106).

Use WordPress Libraries 1.2.3

---

composer.json
includes/class-ckwc-resource-custom-fields.php
tests/_support/Helper/Acceptance/Plugin.php
tests/acceptance/general/ProductCest.php
tests/acceptance/general/RefreshResourcesButtonCest.php
tests/acceptance/settings/SettingAPIKeyAndSecretCest.php
tests/acceptance/settings/SettingCustomFieldsCest.php
tests/wpunit/ResourceCustomFieldsTest.php
tests/wpunit/ResourceFormsTest.php
tests/wpunit/ResourceSequencesTest.php
tests/wpunit/ResourceTagsTest.php

Implements 1.3.1 of the WordPress Libraries, resolving [this issue](https://wordpress.org/support/topic/convertkit-tags-in-woocommerce-not-in-alphabetical-order/), to ensure that Forms, Sequences, Tags and Custom Fields are returned in alphabetical order by name.
- Added `checkSelect*Order()` helper functions to test that the order of `<select>` dropdown option are correct
- WPUnit Resource tests to confirm that `order_by` and `order` properties are honored

Return Resources in correct order

---

tests/wpunit/APITest.php

Adds a unit test to confirm that the Plugin's name and version number is in the user-agent string when making API requests.
- `APITest`: Unit test to confirm that the correct Plugin name and version number are included in the user-agent string when making API requests.

Test User Agent for API requests

---

includes/class-ckwc-order.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php

Adds subscription logic to subscribe the customer to a form, tag or sequence specified within a WooCommerce Coupon, along with tests.
- `SubscribeOnOrderProcessingEventCest:testOptInWhenCheckedWithFormAndSimpleProductWithCouponForm`: Test that defining a ConvertKit Form to subscribe the customer to within a WooCommerce Coupon works when the coupon is applied to the order at checkout.
- `SubscribeOnOrderProcessingEventCest:testOptInWhenCheckedWithFormAndSimpleProductWithCouponTag`: Test that defining a ConvertKit Tag to subscribe the customer to within a WooCommerce Coupon works when the coupon is applied to the order at checkout.
- `SubscribeOnOrderProcessingEventCest:testOptInWhenCheckedWithFormAndSimpleProductWithCouponSequence`: Test that defining a ConvertKit Sequence to subscribe the …

Add subscription logic for WooCommerce Coupons

---

tests/acceptance.suite.yml

Use `--headless=new` in acceptance tests, [as required by Chrome 109+](https://github.com/chromium/chromium/commit/e9c516118e2e1923757ecb13e6d9fff36775d1f4).  Resolves issues with some tests failing.
- Existing tests pass.

Tests: Fix `--headless` flag

---

composer.json
tests/acceptance.suite.yml

Updates the plugin to use [1.3.3](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/1.3.3) of our WordPress Libraries.

Use WordPress Libraries 1.3.3

---

tests/_support/Helper/Acceptance/ConvertKitAPI.php
tests/_support/Helper/Acceptance/Plugin.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance.suite.yml
tests/acceptance/general/CouponCest.php
tests/acceptance/general/ProductCest.php
tests/acceptance/general/RefreshResourcesButtonCest.php
tests/acceptance/general/ReviewRequestCest.php
tests/acceptance/integrations/WooCommerceSubscriptionsSubscribeEventCest.php
tests/acceptance/purchase-data/PurchaseDataCest.php
tests/acceptance/settings/SettingAPIKeyAndSecretCest.php
tests/acceptance/settings/SettingCustomFieldsCest.php
tests/acceptance/settings/SettingDebugLogCest.php
tests/acceptance/settings/SettingEnabledDisabledCest.php
tests/acceptance/settings/SettingImportExportCest.php
tests/acceptance/settings/SettingNameFormatCest.php
tests/acceptance/settings/SettingOptInCheckboxCest.php
tests/acceptance/settings/SettingPurchasesCest.php
tests/acceptance/settings/SettingSubscribeEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php
tests/acceptance/sync-past-orders/SyncPastOrdersCest.php

Improves test performance by performing the following before each test:
- programmatically defining the API Key, Secret and settings,
- writing resources (ConvertKit custom fields, forms, sequences, tags) directly to the database cache, instead of querying the API for them, effectively mocking the API for reading resources
- when querying the API for purchase data, only return the first page of results, instead of all purchases
This improves performance and prevents API rate limits being hit (due to test run in parallel), as the settings screen is only accessed when explicitly required (i.e. for `acceptance/settings` tests).  Previously, this screen would always be accessed for every test, resulting in the API being queried every time to fetch custom fields, forms, sequences and tags.
For …

Improve Test Performance

---

includes/class-ckwc-order.php
tests/acceptance/purchase-data/PurchaseDataCest.php

Fixes [this reported issue](https://wordpress.org/support/topic/integration-not-sending-last-name-to-convertkit/), honoring the `Name Format` setting when:
- the customer is opted in (subscribed) to a form, tag or sequence at checkout, **and**
- send purchase data is enabled
This happens because:
- the customer opts in, with an API request sent to ConvertKit to subscribe the customer, honoring the name format (e.g. First + Last Name),
- the purchase data is then sent via the API separately, and after the customer is subscribed. The `first_name` parameter of the purchase data did not honor the Plugin's name format, resulting in the subscriber's name always being overwritten to their first name.
Whilst the field on ConvertKit for a subscriber does specifically state "First name",  we've …

Fix Purchase Data Name Format

---

includes/class-ckwc-integration.php
includes/class-ckwc-order.php
tests/_support/Helper/Acceptance/ConvertKitAPI.php
tests/_support/Helper/Acceptance/Plugin.php
tests/acceptance/settings/SettingCustomFieldsCest.php

Adds an option to map the WooCommerce Order's last name to a ConvertKit Custom Field.
This opens the possibility of changing the Name Format setting at a later date, given that the name maps to ConvertKit's first name field, and we've provided legacy options to send the first name (which makes sense), last name (which makes less sense) or first and last name (which isn't really what the ConvertKit first name field is for). 
- Added Last Name custom field to all custom field tests, to ensure the data is / is not mapped based on the Plugin's configuration

Add option to map last name to Custom Field

---

admin/class-ckwc-admin-bulk-edit.php
includes/class-ckwc-integration.php
includes/functions.php
tests/_support/Helper/Acceptance/WPAssets.php
tests/acceptance.suite.yml
tests/acceptance/general/ProductCest.php
tests/acceptance/general/RefreshResourcesButtonCest.php
tests/acceptance/settings/SettingAPIKeyAndSecretCest.php
tests/acceptance/sync-past-orders/SyncPastOrdersCest.php
woocommerce-convertkit.php

Removes the double forwardslash when some JS and stylesheets are loaded.
URLs do work with the double forwardslash, but it's best not to have it.
Bumps supported WooCommerce version to the latest version, 7.7.0.
- `ProductCest:testProductFieldsWithIntegrationEnabled`: Confirm JS and CSS is loaded, and the URLs are of the expected format.
- `ProductCest:testQuickEditUsingDefinedResource`: Confirm JS and CSS is loaded, and the URLs are of the expected format.
- `ProductCest:testBulkEditUsingDefinedResource`: Confirm JS and CSS is loaded, and the URLs are of the expected format.
- `SyncPastOrdersCest:testSyncPastOrder`: Confirm JS and CSS is loaded, and the URLs are of the expected format.
- `SettingsAPIKeyAndSecretCest:testSaveBlankSettings`: Confirm JS and CSS is loaded, and the URLs are …

Remove double forwardslash on CSS/JS URLs

---

composer.json
includes/class-ckwc-api.php
includes/class-ckwc-integration.php
includes/class-ckwc-order.php
includes/class-wp-ckwc.php
phpstan.neon.dist
phpstan.neon.example
woocommerce-convertkit.php

Removes most of the remaining PHPStan ignore directives in our code by making the applicable improvements to pass PHPStan static analysis.
Two exclusions remaining:
- `Call to an undefined method WC_Order_Item::get_product()`: PHPStan assumes that a WooCommerce's order item is derived from the `WC_Order_Item` class, when it's derived from the `WC_Order_Item_Product` class, which supports the `get_product()` method.
- `add_action( "woocommerce_update_options_integration_{$this->id}", array( $this, 'process_admin_options' ) )`: WooCommerce's `process_admin_options()` function incorrectly returns data, when WordPress actions should not return data. PHPStan correctly detects this, but we can't control WooCommerce's code here.

Remove most PHPStan ignores

---

.github/workflows/deploy-readme.yml
readme.txt

Adds a [GitHub Action](https://github.com/10up/action-wordpress-plugin-asset-update) to only deploy the readme.txt file if changed in the `main` branch.
This allows changes to be made to the readme file (typically the `Tested up to` WordPress version number), without needing to deploy an entire version update to the Plugin.
Screenshots of this action tested on the ConvertKit for WPForms Plugin, where the `Tested up to` value was changed to WordPress 6.3:

Add deploy readme.txt GitHub Action

---

composer.json
includes/class-ckwc-checkout.php
phpcs.tests.xml
phpcs.xml
resources/backend/js/bulk-edit.js
resources/backend/js/integration.js
resources/backend/js/quick-edit.js
resources/backend/js/refresh-resources.js
resources/backend/js/select2.js
resources/backend/js/sync-past-orders.js
resources/backend/js/synchronous-ajax.js
tests/_support/Helper/Acceptance/Plugin.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/settings/SettingOptInCheckboxCest.php
tests/acceptance/settings/SettingSubscribeEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php
views/backend/post-type/disabled.php
views/backend/settings/sync-past-orders-button.php

Applies changes per the upgrade guide [here](https://github.com/WordPress/WordPress-Coding-Standards/wiki/Upgrade-Guide-to-WordPressCS-3.0.0-for-Developers-of-external-standards), to support `3.0.0` of the WordPress Coding Standards rulesets, released August 21st.
This covers:
- Using `printf` instead of `echo sprintf`
- Spacing for anonymous functions
- Renaming some exclusion rules as they have been renamed in WordPress Coding Standards `3.0.0`

Upgrade to WordPress Coding Standards v3

---

composer.json

`php-webdriver` `1.15.0` [changes the capability key](https://github.com/php-webdriver/php-webdriver/commit/235c2aa07f9e2686f2b876083fc081b00d330d48) that is read to define chromedriver's options when running tests.
This isn't reflected in `wp-browser`, meaning the `chromeOptions` specified aren't honored, resulting in tests failing:
https://github.com/ConvertKit/convertkit-wordpress/blob/plugin-tools-download-log-test/tests/acceptance.suite.yml#L91
Changing `chromeOptions` to match the capability key doesn't resolve, so downgrading the test library for now until this is fixed upstream.

Tests: Downgrade `php-webdriver` to `1.14.0`

---

.github/workflows/coding-standards.yml

Annotates code in a PR when coding standards errors are detected by the GitHub action:

Annotate PR errors

---

composer.json
includes/class-ckwc-api.php

Updates WordPress Libraries to [1.3.9](https://github.com/ConvertKit/convertkit-wordpress-libraries/releases/tag/1.3.9)
Updates localized API error messages.

Updated WordPress Libraries to 1.3.9

---

phpstan.neon.dist
phpstan.neon.example
tests/acceptance/integrations/WooCommerceSubscriptionsSubscribeEventCest.php

For static analysis, removes the `WP_PLUGIN_DIR` ignoreErrors directive, as `phpstan-wordpress` no longer requires this in `1.3.1` and higher.

PHPStan: Remove `WP_PLUGIN_DIR` ignoreErrors directive

---

.github/workflows/test.yml
tests/_support/Helper/Acceptance/Plugin.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/general/ReviewRequestCest.php
tests/acceptance/integrations/WooCommerceSubscriptionsSubscribeEventCest.php
tests/acceptance/purchase-data/PurchaseDataCest.php
tests/acceptance/settings/SettingNameFormatCest.php
tests/acceptance/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php
tests/acceptance/sync-past-orders/SyncPastOrdersCest.php

Refactors the `wooCommerceCreateProductAndCheckoutWithConfig` method by accepting an array of named key/value pairs.
PHP 8's named parameters would be preferable, however with ~ 40% of API requests from this Plugin coming from PHP 7.4 and lower, tests need to be compatible with PHP 7.4 for the time being.

Tests: Refactor `wooCommerceCreateProductAndCheckoutWithConfig` method

---

composer.json
tests/acceptance/settings/SettingDebugLogCest.php
woocommerce-convertkit.php

Updates a failing test due to WooCommerce 8.6.0 now using a table view for logs

Tests: Check for Log in WP_List_Table

---

.github/workflows/test.yml
tests/_data/dump.sql
tests/_support/Helper/Acceptance/ThirdPartyPlugin.php
tests/acceptance/general/ActivateDeactivatePluginCest.php

Updates test DB to run tests in WordPress 6.5, released April 2nd.
Changes code to activate and deactivate the WooCommerce Plugin, due to Plugin bulk actions being disabled in 6.5 when a Plugin (such as WooCommerce third party Plugins) declare dependencies.  Bulk actions are used by wp-browser to activate/deactivate Plugins. See https://core.trac.wordpress.org/ticket/60863

Run Tests against WordPress 6.5

---

resources/backend/css/settings.css

WooCommerce 8.9 changes the CSS class on the `Save changes` button to `button-primary`, meaning the styles to pad the button weren’t being applied.
Includes `.button-primary` in the CSS styles to ensure `Save changes` button has padding applied.

Fix `Save changes` button padding

---

includes/class-ckwc-integration.php

Whilst working on the v4 API integration, there are a few sections that need to fetch the settings link, but weren't using the Plugin supplied `ckwc_get_settings_link` method to do this.

Use `ckwc_get_settings_link` helper method

---

includes/class-ckwc-integration.php
tests/wpunit/APITest.php

Stores the refreshed Access + Refresh Tokens when an API request is made and the Access Token has expired.
- `testAccessTokenRefreshedAndSavedWhenExpired`: Tests that the new Access and Refresh Tokens are saved in the Plugin's settings when the WordPress Libraries make a call to an API endpoint with an expired Access Token.

v4 API: Save updated tokens on refresh

---

.github/workflows/deploy.yml
composer.json
tests/_support/Helper/Acceptance/ConvertKitAPI.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/settings/SettingOAuthCest.php
woocommerce-convertkit.php

Use the ConvertKit-hosted redirect URL with the `2.0` WordPress Libraries.
Updates tests that check the `state` parameter for beginning the OAuth process to its new encoded version.

v4 API: Use ConvertKit-hosted redirect URI

---

includes/class-ckwc-integration.php

The `autoload` parameter of `update_option()` WordPress function prefers either `null` or a boolean.  The string `yes` / `no` [is supported for backward compatibility](https://developer.wordpress.org/reference/functions/update_option/), but for best practice this PR updates it to `true`.

Change `update_option` parameter from `yes` to `true`

---

includes/class-ckwc-order.php
tests/_support/Helper/Acceptance/ConvertKitAPI.php

Fixes [this reported issue](https://linear.app/kit/issue/PLAT-2027/platform-v4-api-issue-post-to-create-a-subscriber-doesnt-appear-to), by calling `create_subscriber` with `state` = `inactive` when a Form is selected as the resource to assign to the subscriber to.

Create subscriber with `inactive` state when a Form option is selected

---

.github/workflows/test.yml
includes/class-ckwc-order.php
tests/acceptance/purchase-data/PurchaseDataCest.php

Adds [this feature request](https://app.intercom.com/a/inbox/e4n3xtxz/inbox/shared/all/conversation/12263830580153?view=List), by adding custom field data to the subscriber created when purchase data is sent to ConvertKit.
Previously, this data would only be sent if the subscribe option was configured (to subscribe to a form, tag, sequence).
- `testSendPurchaseDataWithCustomFieldsOnSimpleProductCheckout`: Test that custom field data is assigned to the subscriber created when purchase data is sent to ConvertKit for a WooCommerce order.

Send Custom Field Data with Purchase Data

---

.github/workflows/test.yml
tests/_support/Helper/Acceptance/WooCommerce.php

Create `wc-logs` directory and set permissions to ensure tests pass.

Tests: Create `wc-logs` folder with permissions

---

includes/class-ckwc-integration.php
includes/class-ckwc-order.php
tests/_support/Helper/Acceptance/ConvertKitAPI.php
tests/_support/Helper/Acceptance/Plugin.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/purchase-data/PurchaseDataCest.php
tests/acceptance/settings/SettingCustomFieldsCest.php
tests/acceptance/subscribe/SubscribeCheckoutBlockOnOrderProcessingEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php

Adds an option to exclude the name from the billing and shipping address when stored as custom fields in ConvertKit, [as requested here](https://linear.app/kit/issue/BCDC-3223/woocommerce-billing-address-issue).
Added the following tests to confirm the name is excluded from the address custom field when this setting is enabled:
- `testSendPurchaseDataWithCustomFieldsAndExcludeNameFromAddressOnSimpleProductCheckout`
- `testOptInWhenCheckedWithFormCustomFieldsAndExcludeNameFromAddressOnSimpleProduct`
- `testOptInWhenCheckedWithFormCustomFieldsAndExcludeNameFromAddressOnSimpleProduct`
- `testOptInWhenCheckedWithFormCustomFieldsAndExcludeNameFromAddressOnSimpleProduct`
- `testOptInWhenCheckedWithFormCustomFieldsAndExcludeNameFromAddressOnSimpleProduct`

Exclude Name from Billing + Shipping Addresses

---

admin/class-ckwc-admin-ajax.php
includes/class-ckwc-order.php
tests/acceptance/sync-past-orders/SyncPastOrdersHPOSCLICest.php
tests/acceptance/sync-past-orders/SyncPastOrdersHPOSCest.php

Fixes [this reported issue](https://linear.app/kit/issue/WP-2/bcdc-wordpress-p3-woocommerce-import-purchases-is-erroring-out-partway#comment-fa4817bb), due to [this change](https://github.com/woocommerce/woocommerce/pull/47457), meaning that the Sync Past Orders functionality could determine which Orders need to be sent to Kit's purchase data API endpoint when WooCommerce's HPOS is not enabled (as was the case with this creator's site), resulting in it attempting to send all Orders.
- `SyncPastOrdersHPOSCest`: Renamed from `SyncPastOrdersCest`. Runs tests with HPOS enabled.
- `SyncPastOrdersHPOSCLICest`: Renamed from `SyncPastOrdersCLICest`. Run tests in CLI with HPOS enabled.
- `SyncPastOrdersCest`: Run tests with HPOS disabled.
- `SyncPastOrdersCLICest`: Run CLI tests with HPOS …

Fix Sync Past Orders when HPOS Disabled

---

.github/workflows/test.yml
composer.json
includes/class-ckwc-integration.php
phpstan.neon.dist
phpstan.neon.example
tests/_support/Helper/Acceptance/Plugin.php

Runs static analysis using the latest [2.0](https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md) version of PHPStan when tests are performed on PHP 7.4 and higher, which is the minimum supported version.
PHPStan 1.x will run on tests using PHP < 7.4.
Includes [this PR](https://github.com/Kit/convertkit-wordpress/pull/747) fix for `_load_textdomain_just_in_time` errors caused by third party Plugins.

Tests: Use PHPStan 2.0

---

composer.json
includes/class-ckwc-order.php
tests/_support/Helper/Acceptance/ConvertKitAPI.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/subscribe/SubscribeCheckoutBlockOnOrderProcessingEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php

Specifies the WordPress site URL as the `referrer` parameter, when the Plugin is configured to subscribe the email address to a Kit Form.
- Updated opt in form tests to assert subscriber is assigned the form and has the expected referrer.

Form Subscribe: Add `referrer` support

---

.github/workflows/test-backward-compat.yml
composer.json
includes/blocks/opt-in/class-ckwc-opt-in-block-integration.php
includes/class-ckwc-checkout.php
includes/class-ckwc-order.php
includes/class-wp-ckwc.php
tests/_support/Helper/Acceptance/ConvertKitAPI.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/backward-compat/BackwardCompatSettingsOptInCheckboxCest.php
tests/acceptance/settings/SettingOptInCheckboxCest.php
tests/acceptance/subscribe/SubscribeCheckoutBlockOnOrderProcessingEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php

WooCommerce 8.9.0, released May 2024, introduced the `woocommerce_register_additional_checkout_field` method, providing a PHP method for registering fields on the WooCommerce Checkout block.
Previously, this method wasn't available, which is why [this PR in December 2023](https://github.com/Kit/convertkit-woocommerce/pull/167) provided an opt-in block for the WooCommerce Checkout block.
This new method is designed to replace the opt-in block, although the opt-in block is retained for installations < 8.9.0 that use the Checkout block experience.
Existing tests pass. Changes to tests made to support:
- WooCommerce Stripe Gateway 9.1.0
- WooCommerce Subscriptions 7.0.0

Register Opt-In Checkbox using `woocommerce_register_additional_checkout_field`

---

includes/class-ckwc-order.php
tests/_support/Helper/Acceptance/WPBulkEdit.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/sync-past-orders/SyncPastOrdersCest.php
tests/acceptance/sync-past-orders/SyncPastOrdersHPOSCest.php
views/backend/settings/sync-past-orders.php

Fixes this reported issue, where refund orders were incorrectly included in the Sync Past Orders functionality of this Plugin, due to the `type` filter missing when fetching Orders needing to be sent to Kit's `purchases` endpoint when WooCommerce's HPOS is enabled.
- `SyncPastOrdersTest:testSyncPastOrderExcludesRefunds`: Test that no sync past orders button is displayed when a WooCommerce Order is refunded.
- `SyncPastOrdersHPOSTest:testSyncPastOrderExcludesRefunds`: Test that no sync past orders button is displayed when a WooCommerce Order is refunded and HPOS is enabled.

Fix Sync Past Orders when Refund Orders exist

---

includes/class-ckwc-order.php
tests/_support/Helper/Acceptance/WooCommerce.php
tests/acceptance/purchase-data/PurchaseDataCest.php
tests/acceptance/subscribe/SubscribeCheckoutBlockOnOrderProcessingEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/acceptance/subscribe/SubscribeOnOrderProcessingEventCest.php
tests/acceptance/sync-past-orders/SyncPastOrdersCLICest.php
tests/acceptance/sync-past-orders/SyncPastOrdersCest.php
tests/acceptance/sync-past-orders/SyncPastOrdersHPOSCLICest.php
tests/acceptance/sync-past-orders/SyncPastOrdersHPOSCest.php

Fixes [this reported issue](https://linear.app/kit/issue/WP-23/kit-for-woocommerce-sync-past-orders-dont-sync-orders-with-invalid-no), where Orders containing no email address are attempted to be sent to the purchases API endpoint through the Sync Past Orders functionality, resulting in expected errors due to there being no email address.
- `testSyncPastOrderExcludesOrdersWithNoEmailAddress`: Test that Orders with no email address are excluded from being sent to Kit's purchases endpoint, in both HPOS and non-HPOS environments.

Sync Past Orders: Exclude Orders with no Email Address

---

includes/class-wp-ckwc.php

Removes the call to `load_plugin_textdomain`, as [it's not needed since WordPress 4.6](https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/#Enhanced-support-for-only-using-PHP-translation-files):
> Reminder: if your plugin or theme is hosted on WordPress.org and is still using load_*_textdomain(), you can remove this call. Since WordPress 4.6, plugins and themes no longer need load_plugin_textdomain() or load_theme_textdomain(). WordPress automatically loads the translations for you when needed. If you still support older WordPress versions or do not host your plugin/theme on WordPress.org, move the function call to a later hook such as init.

Remove `load_plugin_textdomain`

---

includes/class-ckwc-setup.php

Includes the [`tenant_name` parameter](https://github.com/Kit/convertkit/pull/33052) as the WordPress site URL when calling `get_access_token_by_api_key_and_secret()` to fetch an access token using a v3 API Key and Secret, when users upgrade from < 1.8.0 to 1.8.0 or higher.

Include `tenant_name` site URL on upgrade from v3 to v4 API

---

includes/class-ckwc-setup.php
includes/class-wp-ckwc.php
tests/EndToEnd/general/ProductCest.php
tests/EndToEnd/general/UpgradePathsCest.php
tests/EndToEnd/integrations/WooCommerceSubscriptionsSubscribeEventCest.php
tests/EndToEnd/settings/SettingImportExportCest.php
tests/EndToEnd/settings/SettingOAuthCest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersCest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersHPOSCest.php
tests/Support/Data/dump.sql
tests/Support/Helper/ThirdPartyPlugin.php
tests/Support/Helper/WooCommerce.php

[It seems that this chromedriver v134 bug](https://issues.chromium.org/issues/402796660) results in tests failing due to methods such as `click_button` return control to the test before fully completing.  There's also a lot of other repositories having similar issues with a [variety of test frameworks](https://github.com/teamcapybara/capybara/issues/2800).
Fixes tests by ensuring elements are fully loaded before attempting to perform the next step.

Tests: Add compatibility with chromedriver v134

---

includes/class-ckwc-integration.php
includes/class-ckwc-order.php
includes/class-ckwc-setup.php
tests/EndToEnd/general/UpgradePathsCest.php
tests/EndToEnd/purchase-data/PurchaseDataCest.php
tests/EndToEnd/settings/SettingCustomFieldsCest.php
tests/EndToEnd/settings/SettingOAuthCest.php
tests/EndToEnd/subscribe/SubscribeCheckoutBlockOnOrderProcessingEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderProcessingEventCest.php
tests/Support/Helper/KitAPI.php
tests/Support/Helper/Plugin.php
tests/Support/Helper/WooCommerce.php
woocommerce-convertkit.php

WooCommerce 9.8.0 now includes the country name by default when fetching an Order's address using `get_formatted_billing_address` and `get_formatted_shipping_address` methods, which resulted in tests breaking:
Creators will expect the address data in their subscriber's custom fields to remain consistent. Rather than add another exclusion field ([as done for the `Exclude Name from Billing & Shipping Addresses` setting](https://github.com/Kit/convertkit-woocommerce/pull/193)), this PR adds a new `Address Format` setting, allowing creators to choose the precise address data to include in the subscriber's billing and shipping custom fields:
By default, this is configured to include the company name, address, city, state and postcode, to match current behaviour.
For creators upgrading who have …

Custom Fields: Replace `Exclude Name from Billing & Shipping Addresses` with `Address Format` setting

---

.devcontainer/devcontainer.json
.devcontainer/post-create.sh
phpstan-dev.neon

Adds a `devcontainer.json` configuration to facilitate running a dev container locally or in GitHub Codespaces, using [WPVIP's configuration](https://docs.wpvip.com/local-development/github-codespaces/), which provides a ready made nginx, PHP, MySQL and WordPress setup.
Codespace example:
https://fictional-barnacle-7v6rg5pjqq3wxxj-80.app.github.dev
https://fictional-barnacle-7v6rg5pjqq3wxxj-80.app.github.dev/wp-admin/
- User: vipgo
- Pass: password
Codeception (for end to end testing) isn't yet configured, as this requires chromedriver to run in a separate process.

Add `devcontainer` configuration

---

.scripts/build.sh

Improves the `build.sh` script for building a Plugin ZIP file locally, by including the Kit WordPress Libraries from the `vendor` folder, and excluding some other unnecessary assets.  This is occasionally used when troubleshooting specific creator sites and a specific build is needed for debugging an issue.  For published releases to wordpress.org, the [GitHub deploy action](https://github.com/Kit/convertkit-woocommerce/blob/fix-build-script/.github/workflows/deploy.yml) is still used.

Fix `build.sh`

---

includes/class-ckwc-checkout.php
tests/EndToEnd/backward-compat/BackwardCompatSettingsOptInCheckboxCest.php

Fixes [this reported issue](https://wordpress.org/support/topic/fatal-error-on-checkout-6/), where WooCommerce < 8.9.0 uses the `CKWC_Opt_In_Block_Integration` checkout block to render the opt in checkbox, resulting in an error when the `WP_REST_Request` `extensions` property isn't an array.
- `BackwardCompatSettingOptInCheckboxCest:testOptInWhenCheckedWithFormAndSimpleProduct`: Tests that the opt-in checkbox works on checkout when using WooCommerce 8.4.0, with no fatal errors.

Checkout Block: Cast `extensions` as array

---

.github/workflows/coding-standards.yml
.github/workflows/test-backward-compat.yml
.github/workflows/test.yml

Runs tests and coding standards against the latest PHP version, 8.4.

Run Tests and Coding Standards against PHP 8.4

---

tests/EndToEnd/settings/SettingEnabledDisabledCest.php
tests/EndToEnd/settings/SettingOptInCheckboxCest.php
tests/EndToEnd/subscribe/SubscribeCheckoutBlockOnOrderProcessingEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderProcessingEventCest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersCLICest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersCest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersHPOSCLICest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersHPOSCest.php

Adds named arguments to the remaining tests, following https://github.com/Kit/convertkit-woocommerce/pull/228

Tests: Use Named Arguments, Part 2

---

.github/workflows/coding-standards.yml
tests/EndToEnd/general/CouponCest.php
tests/EndToEnd/general/ProductCest.php
tests/EndToEnd/general/RefreshResourcesButtonCest.php
tests/EndToEnd/integrations/WooCommerceSubscriptionsSubscribeEventCest.php
tests/EndToEnd/integrations/WooCommerceSubscriptionsSubscribeEventCheckoutBlock.php
tests/EndToEnd/purchase-data/PurchaseDataCest.php
tests/EndToEnd/settings/SettingEnabledDisabledCest.php
tests/EndToEnd/settings/SettingOptInCheckboxCest.php
tests/EndToEnd/subscribe/SubscribeCheckoutBlockOnOrderProcessingEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderCompletedEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderPendingPaymentEventCest.php
tests/EndToEnd/subscribe/SubscribeOnOrderProcessingEventCest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersCLICest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersCest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersHPOSCLICest.php
tests/EndToEnd/sync-past-orders/SyncPastOrdersHPOSCest.php
tests/Support/Helper/WooCommerce.php

Uses named arguments in Tests, as they run on PHP 8.1 and higher, which supports this.
See https://github.com/Kit/convertkit-woocommerce/pull/229 for further changes, split into two PR's for ease of review.

Tests: Use Named Arguments

---

.scripts/create-plugin-zip.sh
composer.json

Registers a number of commands in the `scripts` section of Composer, which serve as shorthand commands for testing and other common tasks performed in development, to save repetitively typing longer commands with commonly used flags / arguments.
| Command | Description |
|---------|-------------|
| `create-release-assets` | Generates both the language translation template file (POT) and documentation for actions/filters |
| `create-pot` | Generates just the language translation template file (POT) |
| `create-dev-docs` | Generates just the documentation for actions/filters |
| `phpcs` | Runs PHP CodeSniffer on the entire plugin codebase |
| `phpcs-tests` | Runs PHP CodeSniffer specifically on the tests directory using test-specific standards |
| `phpstan` | Runs PHPStan static analysis …

Composer: Add Commands

---

admin/class-ckwc-admin-bulk-edit.php
admin/class-ckwc-admin-post-type.php
resources/backend/css/refresh-resources.css
resources/backend/css/select2.css
resources/backend/js/refresh-resources.js

Improves the refresh resources buttons, by rotating the refresh icon until the update completes. Also moves CSS to its own stylesheet, as we use this across:
- product settings,
- quick/bulk edit
Previously, the button would change its state to disabled, with no on screen indication of what was happening until the button re-enabled when the update completed.

Improve Refresh Resource Button
